package com.revature.demo;

import java.sql.SQLException;

import com.revature.dao.StudentDAO;
import com.revature.dto.AddOrUpdateStudentDTO;
import com.revature.model.Student;

public class Application {

	public static void main(String[] args) {
		
		StudentDAO studentDao = new StudentDAO();
		
		try {
//			List<Student> results = studentDao.getAllStudents();
//			
//			System.out.println(results);
			
//			Student s = studentDao.getStudentById(1);
//			System.out.println(s);
			
//			AddOrUpdateStudentDTO studentToBeAdded = new AddOrUpdateStudentDTO("Megan", "Doe", "Sophmore", 19);
			
			// addStudent takes in an AddOrUpdateStudentDTO object as the input argument, and returns a Student object
			// containing the record that was inserted into the database (with the autogenerated ID)
//			Student insertedRecord = studentDao.addStudent(studentToBeAdded);
//			System.out.println(insertedRecord);
			
//			AddOrUpdateStudentDTO studentToUpdate = new AddOrUpdateStudentDTO("Megan", "Doe", "Sophmore", 19);
//			Student updatedStudent = studentDao.updateStudent(5, studentToUpdate);
//			
//			System.out.println(updatedStudent);
			
//			studentDao.deleteStudentById(5);
			
//			studentDao.deleteAllStudents();
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
	}

}
